name = "KLocality"
version = "0.1.0"
defaultTargets = ["KLocality"]

[[require]]
name = "cslib"
git = "https://github.com/SamuelSchlesinger/cslib.git"
rev = "89619147bf2ef78b8f04c66cbb41546d4757554e"

[[lean_lib]]
name = "KLocality"

[[lean_exe]]
name = "klocality"
root = "Main"
